name: "Setup gh cli"
description: "Setup gh cli in self-hosted runners. This action is to setup gh cli in self-hosted runners"
author: "ksivamuthu"
inputs:
  version: 
    required: false
    description: 'gh cli version to download'
runs:
  using: 'node16'
  main: 'dist/index.js'
