name: "Setup GH CLI"
description: "Setup GH CLI in self-hosted runners. In github cloud hosted runners, gh cli is auto installed. This action is to setup gh cli in self-hosted runners"
author: "ksivamuthu"
inputs:
  version: 
    required: false
    description: 'gh cli version to download'
runs:
  using: 'node16'
  main: 'dist/index.js'
